VERSION=0.4

# Base dirs
MYEXPOS_PATH=$HOME/myexpos
XFS_INTERFACE_PATH=$MYEXPOS_PATH/xfs-interface
EXPL_PROGRAMS_DIR=$MYEXPOS_PATH/expl/expl_progs
SPL_PROGRAMS_DIR=$MYEXPOS_PATH/spl/spl_progs

# OS
OS_PATH_SPL=$SPL_PROGRAMS_DIR/os_startup.spl
OS_PATH_XSM=$SPL_PROGRAMS_DIR/os_startup.xsm

# Routines
HALT_ROUTINE_DIR=$SPL_PROGRAMS_DIR/haltprog.spl
HALT_ROUTINE_DIR_XSM=$SPL_PROGRAMS_DIR/haltprog.xsm
EXHANDLER_ROUTINE_DIR=$SPL_PROGRAMS_DIR/haltprog.spl
EXHANDLER_ROUTINE_DIR_XSM=$SPL_PROGRAMS_DIR/haltprog.xsm
TIMER_ROUTINE_DIR=$SPL_PROGRAMS_DIR/sample_timer.spl
TIMER_ROUTINE_DIR_XSM=$SPL_PROGRAMS_DIR/sample_timer.xsm
INT7_ROUTINE_DIR=$SPL_PROGRAMS_DIR/INT7.spl
INT7_ROUTINE_DIR_XSM=$SPL_PROGRAMS_DIR/INT7.xsm
IDLE_ROUTINE_DIR=$EXPL_PROGRAMS_DIR/idle.expl
IDLE_ROUTINE_DIR_XSM=$EXPL_PROGRAMS_DIR/idle.xsm

